website1: https://test-stand.gb.ru/gateway/login
website2: https://test-stand.gb.ru/api/posts
website3: https://test-stand.gb.ru/gateway/posts
username: Fred123
password: 17fe38c02d
title1: New post phyton
description1: new post
content1: content
